frontend_repo: "https://github.com/SupeRWiNdz/DevOps-Frontend"
backend_repo: "https://github.com/SupeRWiNdz/DevOps-Backend"
devops_repo: "https://github.com/SupeRWiNdz/DevOps"

project_root: "/home/danya/projects"
compose_file: "/home/danya/projects/DevOps/docker-compose.yaml"