- name: Clone repositories
  include_tasks: subtasks/clone.yml
  tags: [clone]

- name: Install Docker
  include_tasks: subtasks/install.yml
  tags: [install]

- name: Start containers
  include_tasks: subtasks/start.yml
  tags: [start]