- hosts: host1
  become: yes
  roles:
    - role: deploy
      tags: [deploy]
  
  tasks:
    - name: Include Docker installation
      include_tasks: roles/deploy/tasks/subtasks/install_docker.yml
      tags: [install_docker]